manage_club/club/urls.py
from django.urls import re_path as url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "club"

urlpatterns = [
    url(r'^create-club/$',views.create_club,name="create_club"),
    url(r'^delete-club/$',views.delete_club,name="delete_club"),
    url(r'^list-club/$',views.list_club,name="list_club"),
    url(r'^club-detail/(?P<club_id>\d+)/$',views.list_club_detail,name="club_detail"),
    url(r'^send-message/$',views.send_message,name="send_message"),
    url(r'^my-send/$',views.my_send,name="my_send"),
    url(r'^my-send-type/(?P<type>\d+)/$', views.my_send_type, name="my_send_type"),
    url(r'^my-receive/$',views.my_recceived,name="my_receive"),
    url(r'^message-detail/(?P<message_id>\d+)/$',views.message_detail,name="message_detail"),
    url(r'^join-club/(?P<club_id>\d+)/$',views.join_club,name="join_club"),
    url(r'^exit-club/$',views.exit_club,name="exit_club"),
    url(r'^confirm-join/(?P<club_id>\d+)/$',views.confirm_join,name="confirm_join"),
    url(r'^my_club/$',views.my_club,name="my_club"),
    url(r'^manage-Myclub/$',views.manage_Myclub,name="manage_Myclub"),
    url(r'^manage-member/(?P<club_id>\d+)/$',views.manage_member,name="manage_member"),
    url(r'^delete-member/(?P<club_id>\d+)/$',views.delete_member,name="delete_member"),
    url(r'^manage-clubInfo/(?P<club_id>\d+)/$',views.manage_clubInfo,name="manage_clubInfo"),
    url(r'^club-image/(?P<club_id>\d+)/$',views.club_image,name="club_image"),
    url(r'^create-activity/(?P<club_id>\d+)/$',views.create_activity,name="create_activity"),
    url(r'^list-activity/(?P<club_id>\d+)/$',views.list_activity,name="list_activity"),
    url(r'^activity-detail/(?P<activity_id>\d+)/(?P<club_id>\d+)/$',views.activity_detail,name="activity_detail"),
    url(r'^activity-detail/(?P<activity_id>\d+)/$',views.activity_detail_version,name="activity_detail"),
    url(r'^delete-activity/$',views.delete_activity,name="delete_activity"),
    url(r'^all-activity/$',views.all_activity,name="all_activity"),
    url(r'^my-activity/$',views.my_activity,name="my_activity"),
    url(r'^fan-Club/$',views.fan_Club,name="fan_Club"),

    url(r'^create-ad/(?P<club_id>\d+)/$',views.create_ad,name="create_ad"),
    url(r'^list-ads/(?P<club_id>\d+)/$',views.list_ads,name="list_ads"),
    url(r'^manage_ad/(?P<club_id>\d+)/$',views.manage_ad,name="manage_ad"),
    url(r'^view_ad_lists/(?P<club_id>\d+)/$',views.view_ad_lists,name="view_ad_lists"),
    url(r'^ad-detail-owner/(?P<ad_id>\d+)/$',views.ad_detail_owner,name="ad_detail_owner"),
    url(r'^ad-detail-other/(?P<ad_id>\d+)/$',views.ad_detail_other,name="ad_detail_other"),
    url(r'^ad-detail-edit/(?P<ad_id>\d+)/$',views.ad_detail_edit,name="ad_detail_edit"),
    url(r'^delete_ad/$',views.delete_ad,name="delete_ad"),
]

manage_club/manage_club/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import re_path as url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^club/', include('club.urls', namespace='club')),
    url(r'^home/',include("home.urls",namespace='home')),
    url(r'^trade/',include('trade.urls',namespace='trade')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

manage_club/trade/urls.py
from django.urls import re_path as url
from . import views

app_name = "trade"

urlpatterns = [
    url(r'^create-good/(?P<club_id>\d+)/$',views.create_good,name="create_good"),
    url(r'^list-goods/(?P<club_id>\d+)/$',views.list_goods,name="list_goods"),
]

manage_club/trade/models.py
from django.db import models
from club.models import Club

class GoodType(models.Model):
    type = models.CharField(max_length=20)
    def __str__(self):
        return self.type

class Commodity(models.Model):
    name = models.CharField(max_length=50,help_text="不超过50个字符")
    status = models.CharField(max_length=10,default="selling")              #两种类型：selling和sold
    contact = models.CharField(max_length=100)
    expense = models.FloatField()
    intro = models.TextField(max_length=500,help_text="不超过500个字符")
    photo = models.ImageField(upload_to='images/%Y/%m/%d',default="static/images/face.jpg")
    owner = models.ForeignKey(Club,related_name="owner",on_delete=models.CASCADE)
    Type = models.ManyToManyField(GoodType,related_name="Type",blank=True)

manage_club/trade/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import GoodType,Commodity

class CommodityForm(forms.ModelForm):
    class Meta:
        model = Commodity
        fields = ("name","expense","intro","Type","contact","photo",)

manage_club/trade/views.py
import json

from django.shortcuts import render
from .models import GoodType,Commodity
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.decorators.http import require_GET, require_POST
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from club.models import Club
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.db.models import QuerySet
from .forms import CommodityForm
from .models import Commodity,GoodType

@login_required(login_url='account/login')
@csrf_exempt
def create_good(request,club_id):
    if request.method == "GET":
        good_form = CommodityForm()
        types = GoodType.objects.all()
        return render(request,"trade/create_good.html",{"good_form":good_form,"types":types,"club_id":club_id})
    else:
        club = Club.objects.get(id=club_id)
        types = request.POST["types"]
        name = request.POST['name']
        expense = request.POST['expense']
        intro = request.POST['intro']
        contact = request.POST['contact']
        photo = request.FILES.get('photo')
        print(photo)
        new_good = Commodity()
        new_good.status = "selling"
        new_good.owner = club
        new_good.photo = photo
        new_good.name = name
        new_good.expense = expense
        new_good.intro = intro
        new_good.contact = contact
        new_good.save()
        if types:
            for type in json.loads(types):
                type = GoodType.objects.get(type=type)
                new_good.Type.add(type)
        return HttpResponse("1")


@login_required(login_url='account/login')
def list_goods(request,club_id):
    club = Club.objects.get(id=club_id)
    goods = club.owner.all()
    paginator = Paginator(goods, 3)
    page = request.GET.get('page')
    try:
        current_page = paginator.page(page)
        goods = current_page.object_list
    except PageNotAnInteger:
        current_page = paginator.page(1)
        goods = current_page.object_list
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)
        goods = current_page.object_list
    return render(request,"trade/list_goods.html",{"club_id":club_id,"goods":goods,"page":current_page})

manage_club/templates/trade/create_good.html
{% extends "base.html" %}
{% load static %}
{% block title %}create good{% endblock %}
{% block content %}
<div style="margin-left: 10px">
    <form class="form-horizontal" action="." method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="row" style="margin-top: 10px">
            <div class="col-md-2 text-right"><span>商品名称：</span></div>
            <div class="col-md-10 text-left">{{ good_form.name }}</div>
        </div>

        <div class="row" style="margin-top: 10px">
            <div class="col-md-2 text-right"><span>商品标签：</span></div>
            <div class="col-md-10 text-left">
                {% for type in types %}
                <label class="checkbox-inline">
                    <input class="tagcheckbox" type="checkbox" id="{{ type.id }}" name="good_type" value="{{ type.type }}">{{ type.type }}
                </label>
                {% empty %}
                <p>You have not type for goods.</a></p>
                {% endfor %}
            </div>
        </div>

        <div class="row" style="margin-top: 10px">
            <div class="col-md-2 text-right"><span>商品价格：</span></div>
            <input type="text" class="text-left col-md-4" id="id_expense">
        </div>
        <div class="row" style="margin-top: 10px">
            <div class="col-md-2 text-right"><span>商品介绍：</span></div>
            <input type="text" class="text-left col-md-6" id="id_intro">
        </div>
        <div class="row" style="margin-top: 10px">
            <div class="col-md-2 text-right"><span>联系方式：</span></div>
            <input type="text" class="text-left col-md-6" id="id_contact">
        </div>
        <div class="row" style="margin-top: 10px">
            <input type="file" name="image_file" id="image_file">
        </div>
        <div class="row">
            <input type="button" class="btn btn-primary btn-lg" value="发布物品" onclick="publish_good()">
        </div>
    </form>
</div>

<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'js/json2.js' %}"></script>
<script type="text/javascript">
    function publish_good(){
        var name = $("#id_name").val();
        var expense = $("#id_expense").val();
        var intro = $("#id_intro").val();
        var contact = $("#id_contact").val();
        var photo = $("#image_file").val();
        console.log("photo:",photo)
        var good_types = [];
        $.each($("input[name='good_type']:checked"),function (){good_types.push($(this).val());});
        $.ajax({
            url:"{% url 'trade:create_good' club_id %}",
            type:"POST",
            data:{"name":name,
                "expense":expense,
                "intro":intro,
                "contact":contact,
                "photo":photo,
                "types":JSON.stringify(good_types)},
            success:function (e){
                if(e=="1"){
                    layer.msg("successful!");
                }
                else if(e=="2"){
                    layer.msg("Sorry~");
                }
            },
        });
    }
</script>
{% endblock %}

manage_club/templates/trade/list_goods.html
{% extends "base.html" %}
{% load static %}
{% block title %}Goods{% endblock %}
{% block content %}
<div class="row text-center vertical-middle-sm">
    <h1>已发布闲置物品👇</h1>
</div>
<div class="container">
    {% for good in goods %}
    <div class="list-group">
        <a href="#" class="list-group-item active" style="margin-right: 100px">
            <h4 class="list-group-item-heading">{{ good.name }}</h4></a>
            <p class="list-group-item-text">物品状态:：{{ good.status }}</p>
            <p class="list-group-item-text">物品价格:：{{ good.expense }}</p>
            <p class="list-group-item-text">物品介绍：{{ good.intro |slice:'70'|linebreaks }}</p>
    </div>
    {% empty %}
    <h4 class="text-center">还没有商品捏~</h4>
    {% endfor %}
    {% include "paginator.html" %}
</div>

{% endblock %}