manage_club/account/urls.py
from django.urls import re_path as url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path
from captcha.views import captcha_image
from django.conf.urls import include


app_name='account'

urlpatterns = [
    url(r'^login/$',views.user_login,name="user_login"),
    path(r'logout/', auth_views.LogoutView.as_view(template_name="account/logout.html"), name='logout'),
    url(r'^register/$',views.register,name="user_register"),
    path('password-change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html',
                                               success_url='../password-change-done/'), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    url(r'^password-reset/$',auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html",
                                                          email_template_name="account/password_reset_email.html",
                                                          subject_template_name="account/password_reset_subject.txt",
                                                          success_url="../password-reset-done"),name="password_reset"),
    url(r'^password-reset-done/$',auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"),name="password_Reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html",success_url="../../../password-reset-complete/"),
        name="password_reset_confirm"),
    url(r'^password-reset-complete/$',auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_complete.html"),
        name="password_reset_complete"),
    url(r'^my-information/$',views.myself,name="my_information"),
    url(r'^my-information/(?P<user_id>\d+)/$',views.myself_version,name="my_information"),
    url(r'^edit-my-information/$',views.myself_edit,name="edit_my_information"),
    url(r'^my-image/$',views.my_image,name="my_image"),
    url(r'^search/$',views.search,name="search"),
    
    path('captcha/', include('captcha.urls')),

]

manage_club/club/urls.py
from django.urls import re_path as url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "club"

urlpatterns = [
    url(r'^create-club/$',views.create_club,name="create_club"),
    url(r'^delete-club/$',views.delete_club,name="delete_club"),
    url(r'^list-club/$',views.list_club,name="list_club"),
    url(r'^club-detail/(?P<club_id>\d+)/$',views.list_club_detail,name="club_detail"),
    url(r'^send-message/$',views.send_message,name="send_message"),
    url(r'^my-send/$',views.my_send,name="my_send"),
    url(r'^my-send-type/(?P<type>\d+)/$', views.my_send_type, name="my_send_type"),
    url(r'^my-receive/$',views.my_recceived,name="my_receive"),
    url(r'^message-detail/(?P<message_id>\d+)/$',views.message_detail,name="message_detail"),
    url(r'^join-club/(?P<club_id>\d+)/$',views.join_club,name="join_club"),
    url(r'^exit-club/$',views.exit_club,name="exit_club"),
    url(r'^confirm-join/(?P<club_id>\d+)/$',views.confirm_join,name="confirm_join"),
    url(r'^my_club/$',views.my_club,name="my_club"),
    url(r'^manage-Myclub/$',views.manage_Myclub,name="manage_Myclub"),
    url(r'^manage-member/(?P<club_id>\d+)/$',views.manage_member,name="manage_member"),
    url(r'^delete-member/(?P<club_id>\d+)/$',views.delete_member,name="delete_member"),
    url(r'^manage-clubInfo/(?P<club_id>\d+)/$',views.manage_clubInfo,name="manage_clubInfo"),
    url(r'^club-image/(?P<club_id>\d+)/$',views.club_image,name="club_image"),
    url(r'^create-activity/(?P<club_id>\d+)/$',views.create_activity,name="create_activity"),
    url(r'^list-activity/(?P<club_id>\d+)/$',views.list_activity,name="list_activity"),
    url(r'^activity-detail/(?P<activity_id>\d+)/(?P<club_id>\d+)/$',views.activity_detail,name="activity_detail"),
    url(r'^activity-detail/(?P<activity_id>\d+)/$',views.activity_detail_version,name="activity_detail"),
    url(r'^delete-activity/$',views.delete_activity,name="delete_activity"),
    url(r'^all-activity/$',views.all_activity,name="all_activity"),
    url(r'^my-activity/$',views.my_activity,name="my_activity"),
    url(r'^fan-Club/$',views.fan_Club,name="fan_Club"),

    url(r'^create-ad/(?P<club_id>\d+)/$',views.create_ad,name="create_ad"),
    url(r'^list-ads/(?P<club_id>\d+)/$',views.list_ads,name="list_ads"),
    url(r'^manage_ad/(?P<club_id>\d+)/$',views.manage_ad,name="manage_ad"),
    url(r'^view_ad_lists/(?P<club_id>\d+)/$',views.view_ad_lists,name="view_ad_lists"),
    url(r'^ad-detail-owner/(?P<ad_id>\d+)/$',views.ad_detail_owner,name="ad_detail_owner"),
    url(r'^ad-detail-other/(?P<ad_id>\d+)/$',views.ad_detail_other,name="ad_detail_other"),
    url(r'^ad-detail-edit/(?P<ad_id>\d+)/$',views.ad_detail_edit,name="ad_detail_edit"),
    url(r'^delete_ad/$',views.delete_ad,name="delete_ad"),
]

manage_club/manage_club/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import re_path as url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^club/', include('club.urls', namespace='club')),
    url(r'^home/',include("home.urls",namespace='home')),
    url(r'^trade/',include('trade.urls',namespace='trade')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

manage_club/club/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Club,Activity,message,InClub,Advertisement
from django.db import models

class ClubCreateForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ("name","club_id","Aboutme",)

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ("name","begin_date","end_date","description",)

class messageForm(forms.ModelForm):
    class Meta:
        model = message
        fields = ("content","receiver_name",)

class ClubForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ("name","club_id","Aboutme")

class CreateAdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = ("title","content","video","attach",)

class AdvertisementForm(forms.ModelForm):
    class Meta:
        model = Advertisement
        fields = ("title","content","video","attach","show",)

manage_club/club/views.py
from itertools import chain
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views.decorators.http import require_GET, require_POST
from .models import message, Activity
from .forms import ClubCreateForm, ActivityForm
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import InClub,Club,Advertisement
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .forms import messageForm
from django.db.models import QuerySet, Q
from .forms import ClubForm,CreateAdvertisementForm,AdvertisementForm
from account.forms import SearchForm

@login_required(login_url='/account/login/')
@csrf_exempt
def create_club(request):
    if request.method == "GET":
        club_form = ClubCreateForm()
        return render(request,"club/create_club.html",{"club_form":club_form})
    else:
        club_form = ClubCreateForm(request.POST)
        if club_form.is_valid():
            new_club = club_form.save(commit=False)
            new_club.lead_name = request.user.username
            new_club.leader = request.user
            new_club.save()

            try:
                inclub = InClub.objects.get(member=request.user)
                inclub.In_club.add(new_club)
                inclub.save()
            except:
                inclub = InClub()
                inclub.member = request.user
                inclub.save()
                inclub.In_club.add(new_club)

            return HttpResponseRedirect(reverse('club:list_club'))
        else:
            return HttpResponse("The input in invalid~")

@login_required(login_url='/account/login/')
@csrf_exempt
def delete_club(request):
    club_id = request.POST['club_id']
    club = Club.objects.get(id=club_id)
    if club.leader != request.user:
        return HttpResponse("NoLeader")
    try:
        #删除Inclub
        inclubs = club.In_club.all()
        for inclub in inclubs:
            inclub.In_club.remove(club)
        #删除activity
        activities = club.launch.all()
        for activity in activities:
            activity.delete()
        #删除ad
        ads = club.advertisement.all()
        for ad in ads:
            ad.delete()
        #删除粉丝
        club.fans.clear()
        #删除社团
        club.delete()
        return HttpResponse("right")
    except:
        return HttpResponse("deleteError")


@login_required(login_url='/account/login/')
def list_club(request):
    if request.method == "GET":
        search_form = SearchForm()
        clubs = Club.objects.all()
        paginator = Paginator(clubs,3)
        page = request.GET.get('page')
        try:
            current_page = paginator.page(page)
            clubs = current_page.object_list
        except PageNotAnInteger:
            current_page = paginator.page(1)
            clubs = current_page.object_list
        except EmptyPage:
            current_page = paginator.page(paginator.num_pages)
            clubs = current_page.object_list

        return render(request,"club/list_club.html",{"clubs":clubs,"page":current_page,"search_form":search_form})
    else:
        search_form = SearchForm(request.POST)
        if search_form.is_valid():
            keyword = request.POST['keyword']
            try:
                clubs = Club.objects.filter(name__icontains=keyword)
                paginator = Paginator(clubs, 3)
                page = request.GET.get('page')
                try:
                    current_page = paginator.page(page)
                    clubs = current_page.object_list
                except PageNotAnInteger:
                    current_page = paginator.page(1)
                    clubs = current_page.object_list
                except EmptyPage:
                    current_page = paginator.page(paginator.num_pages)
                    clubs = current_page.object_list
                return render(request, "club/list_club.html",
                              {"search_form": search_form, "clubs": clubs, "page": current_page})
            except:
                clubs = Club.objects.none()
                paginator = Paginator(clubs, 3)
                page = request.GET.get('page')
                try:
                    current_page = paginator.page(page)
                    clubs = current_page.object_list
                except PageNotAnInteger:
                    current_page = paginator.page(1)
                    clubs = current_page.object_list
                except EmptyPage:
                    current_page = paginator.page(paginator.num_pages)
                    clubs = current_page.object_list
                return render(request,"club/list_club.html",
                              {"search_form": search_form, "clubs": clubs, "page": current_page})
        else:
            return HttpResponse("1")
@login_required(login_url='/account/login/')
@require_GET
def list_club_detail(request,club_id):
    club = Club.objects.get(id=club_id)
    name = request.user.username
    user = User.objects.get(id=request.user.id)
    try:
        theman = InClub.objects.get(member=user)
    except:
        theman = InClub()
    members = club.In_club.all()
    if theman in members:
        type = "1"
    else:
        type = "2"

    return render(request,"club/club_detail.html",{"club":club,"type":type,"name":name})

@login_required(login_url='/account/login/')
@csrf_exempt
def send_message(request):
    if request.method == "POST":
        message_form = messageForm(data=request.POST)
        if message_form.is_valid():
            message = message_form.save(commit=False)
            message.sender = request.user
            try:
                receiver = User.objects.get(username=message.receiver_name)
                message.reciver = receiver
                message.save()
                return HttpResponseRedirect(reverse("club:my_send"))
            except:
                return HttpResponse("用户不存在！")
        else:
            return HttpResponse("2")
    else:
        message_form = messageForm()
        return render(request, 'club/send_message.html',{"message_form":message_form})

@login_required(login_url='/account/login/')
def my_send(request):
    if request.method == "GET":
        search_form = SearchForm()
        messages = message.objects.filter(sender=request.user)
        paginator = Paginator(messages,3)
        page = request.GET.get('page')
        try:
            current_page = paginator.page(page)
            messages = current_page.object_list
        except PageNotAnInteger:
            current_page = paginator.page(1)
            messages = current_page.object_list
        except EmptyPage:
            current_page = paginator.page(paginator.num_pages)
            messages = current_page.object_list
        return render(request,"club/my_send.html",{"messages":messages,"page":current_page,"search_form":search_form})
    else:
        search_form = SearchForm(request.POST)
        if search_form.is_valid():
            keyword = request.POST['keyword']
            try:
                messages = message.objects.filter(receiver_name=keyword)
                paginator = Paginator(messages, 3)
                page = request.GET.get('page')
                try:
                    current_page = paginator.page(page)
                    messages = current_page.object_list
                except PageNotAnInteger:
                    current_page = paginator.page(1)
                    messages = current_page.object_list
                except EmptyPage:
                    current_page = paginator.page(paginator.num_pages)
                    messages = current_page.object_list
                return render(request,"club/my_send.html",{"search_form":search_form,"messages":messages,"page":current_page})
            except:
                messages = message.objects.none()
                paginator = Paginator(messages, 3)
                page = request.GET.get('page')
                try:
                    current_page = paginator.page(page)
                    messages = current_page.object_list
                except PageNotAnInteger:
                    current_page = paginator.page(1)
                    messages = current_page.object_list
                except EmptyPage:
                    current_page = paginator.page(paginator.num_pages)
                    messages = current_page.object_list
                return render(request,"club/my_send.html",{"search_form":search_form,"messages":messages,"page":current_page})
        else:
            return HttpResponse("2")       #表单错误


@login_required(login_url='/account/login/')
def my_send_type(request,type):
    if request.method == "GET":
        search_form = SearchForm()
        if type == "1":
            messages = message.objects.filter(sender=request.user,receiver_read="yes")
        else:
            messages = message.objects.filter(sender=request.user,receiver_read="no")
        paginator = Paginator(messages,3)
        page = request.GET.get('page')
        try:
            current_page = paginator.page(page)
            messages = current_page.object_list
        except PageNotAnInteger:
            current_page = paginator.page(1)
            messages = current_page.object_list
        except EmptyPage:
            current_page = paginator.page(paginator.num_pages)
            messages = current_page.object_list
        return render(request,"club/my_send_type.html",{"messages":messages,"page":current_page,"search_form":search_form,"type":type})
    else:
        search_form = SearchForm(request.POST)

manage_club/templates/club/club_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ club.name }}{% endblock %}

{% block content %}
{% with total_fans=club.fans.count fans=club.fans.all %}

<style>
    /* 添加你的自定义样式 */

    body {
        background-image: url("{% static './images/background2.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;

    }


    .club-info-container {
        margin-top: 20px;
        position: relative;
    }


    .club-info-header {
        margin-bottom: 20px;
    }
    .club-info-header h1 {
        font-family: Arial, sans-serif;
        font-size: 29px;
        font-weight: bold;
        letter-spacing: 2px;
    }

    .club-info-stats {
        margin-bottom: 20px;
    }

    .club-info-stats .glyphicon {
        margin-right: 5px;
        font-size: 12px;
    }

    .glyphicon_style {
        color: gold; /* 设置颜色为金色 */
    }

    .follower_font {
        font-family: sans-serif;
        font-size: 15px;
        font-weight: bold;
        color: #4879e0;
    }

    .club-info-details {
        margin-bottom: 20px;
    }

    .club-info-details .row {
        margin-bottom: 10px;
    }

    .club-info-details .col-md-4 {
        text-align: right;
        font-size: 20px;
        font-weight: bold;
        color: #666;
    }

    .club-info-details .col-md-8 {
        font-size: 18px;
        text-align: left;
        color: #333;
    }

    .club-info-actions {
        margin-bottom: 20px;
    }

    .club-info-actions button {
        margin-right: 10px;
    }

    .club-info-followers {
        margin-top: 20px;
        margin-bottom: 20px;
        color: #a0a5b1;
    }

    .club-info-followers p {
        margin-bottom: 5px;
    }

    .club-info-photo {
    position: absolute;
    top: 40%;
    left: 65%;
    transform: translate(-50%, -50%);
    }

    .club-info-photo img {
        width: 150px;
        height: 150px;
        border-radius: 50%;
    }


</style>

<button onclick="goBack()">返回上一页</button>

<script>
function goBack() {
  history.back();
}
</script>

<div class="row text-center vertical-middle-sm club-info-container">
    <div class="club-info-header">
        <h1>{{ club.name }}社团的基本信息</h1>
    </div>

    <div class="row club-info-stats">
        <div class="col-md-12">
            <span class="glyphicon glyphicon-star glyphicon_style"></span>
            <span class="follower_font">{{ total_fans }} follower{{ total_fans | pluralize }}</span>
        </div>
    </div>

    <div class="row club-info-details">
        <div class="col-md-4"><span>社团名称：</span></div>
        <div class="col-md-8">{{ club.name }}</div>
    </div>

    <div class="row club-info-details">
        <div class="col-md-4"><span>社长姓名：</span></div>
        <div class="col-md-8">{{ club.lead_name }}</div>
    </div>

    <div class="row club-info-details">
        <div class="col-md-4"><span>社团宣言：</span></div>
        <div class="col-md-8">{{ club.club_id }}</div>
    </div>

    <div class="row club-info-details">
        <div class="col-md-4"><span>团内人数：</span></div>
        <div class="col-md-8">{{ club.num_of_mem }}</div>
    </div>

    <div class="row club-info-details">
        <div class="col-md-4"><span>社团简介：</span></div>
        <div class="col-md-8">{{ club.Aboutme }}</div>
    </div>

    <div>
        <a href="{% url 'club:view_ad_lists' club.id %}" style="font-size: 20px;">查看社团广告</a>
    </div>

    <div class="club-info-actions">
        {% if name == club.lead_name %}
            <button class="btn btn-primary btn-lg" style="margin-top: 20px; font-size: 24px; width: 180px;" onclick="delete_club({{ club.id }})">解散社团</button>
        {% else %}
            {% if type == "2" %}
            <a href="{% url 'club:join_club' club.id %}">
                <button class="btn btn-primary btn-lg" style="margin-top: 20px; font-size: 24px; width: 180px;">我要加入!</button>
            </a>
            {% else %}
                <button class="btn btn-primary btn-lg" style="margin-top: 20px; font-size: 24px; width: 180px;" onclick="exit_club({{ club.id }})">我要退出!</button>
            {% endif %}
        {% endif %}
        <p style="margin-top: 30px; font-size: 20px;">
            <a onclick="fan_Club({{ club.id }},'follow')" href="#" style="margin-right: 10px;">
                <span class="glyphicon glyphicon-thumbs-up" ></span>follow
            </a>
            <a onclick="fan_Club({{ club.id }},'unfollow')" href="#" style="margin-left: 10px;">
                <span class="glyphicon glyphicon-thumbs-down"></span>unfollow
            </a>
        </p>
    </div>


    <div class="row">
        <div class="col-md-6 club-info-photo">
            {% if club.photo %}
            <img name="club_face" src="{{ club.photo | striptags }}" class="img-circle" id="club_photo">
            {% else %}
            <img name="user_face" src="{% static 'images/op.png' %}" class="img-circle" id="my_photo">
            {% endif %}
        </div>
    </div>
</div>


<script src="{% static 'js/layer.js' %}"></script>
<script src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript">
    function fan_Club(id, action) {
        $.ajax({
            url: "{% url 'club:fan_Club' %}",
            type: "POST",
            data: { "id": id, "action": action },
            success: function (e) {
                if (e == "1") {
                    layer.msg("感谢关注！");
                    setTimeout(function() {window.location.reload();}, 500); // 2000 毫秒等于 2 秒
                }
                else {
                    layer.msg("我会继续努力~");
                    setTimeout(function() {window.location.reload();}, 500);
                }
            },
        });
    }
</script>
<script type="text/javascript">
    function exit_club(club_id){
        var index = layer.open({
            type: 1,
            skin:"layui-layer-rim",
            area: ["400px","200px"],
            title: "Comfirmation Exit",
            content: '<div class="text-center" style="margin-top: 20px"><p>确定要退出嘛~</p></div>',
            btn: ['Yes','No'],
            yes: function (index,layero){
                $.ajax({
                    url: "{% url 'club:exit_club' %}",
                    type: "POST",
                    data: {"club_id":club_id},
                    success: function (e){
                        if(e=="1"){
                            layer.msg("You have exit~");
                            setTimeout(function() {window.location.reload();}, 500); // 2000 毫秒等于 2 秒
                        }
                        else{
                            layer.msg("delete error!");
                            setTimeout(function() {window.location.reload();}, 500); // 2000 毫秒等于 2 秒
                        }
                    },
                });
            },
        });
    }
</script>

<script type="text/javascript">
    function delete_club(club_id){
        var index = layer.open({
            type: 1,
            skin:"layui-layer-rim",
            area: ["400px","200px"],
            title: "Comfirmation Exit",
            content: '<div class="text-center" style="margin-top: 20px"><p>确定要删除社团嘛~确定要删除的话请输入“我确定”</p></div><input type="text" id="ensure">',
            btn: ['狠心删除！','我再想想...'],
            yes: function (index,layero){
                ensurement = $("#ensure").val()
                $.ajax({
                    url: "{% url 'club:delete_club' %}",
                    type: "POST",
                    data: {"club_id":club_id,"ensurement":ensurement},
                    success: function (e){
                        if(e=="right"){
                            layer.msg("You have delete it~");
                            window.location.href = "{% url 'club:my_club' %}";
                        }
                        else if(e=="NoLeader"){
                            layer.msg("你没有权限！!");
                            setTimeout(function() {window.location.reload();}, 500); // 2000 毫秒等于 2 秒
                        }
                        else{
                            layer.msg("删除错误！");
                            setTimeout(function() {window.location.reload();}, 500); // 2000 毫秒等于 2 秒
                        }
                    },
                });
            },
        });
    }
</script>
{% endwith %}
{% endblock %}

manage_club/templates/club/leftslider.html
<div class="bg-info">
    <div class="text-center" style="margin-top: 10px">
        <p><h4>发出的信息</h4></p>
        <p><a href="{% url 'club:my_send' %}">全部信息</a></p>
        <p><a href="{% url 'club:my_send_type' 1 %}">对方已读</a></p>
        <p><a href="{% url 'club:my_send_type' 2  %}">对方未读</a></p>
    </div>
</div>

manage_club/templates/club/manage_Myclub.html
{% extends "base.html" %}
{% load static %}
{% block title %}articles{% endblock %}
{% block content %}

<style>
        .block {
            background-color: #ffffff;
            display: flex;
            align-items: center;
            margin-bottom: 1px;
            margin-top: -15px;
            padding-top: 10px;
            border-top: 1.5px solid #e8e8e8;
        }

        .block1 {
            background-color: #ffffff;
            padding: 10px;
            display: flex;
            align-items: center;
            margin-bottom: -5px;
            margin-top:3px;
        }

        .first_text {
            /* 文本的样式 */
            margin-right: 150px; /* 右侧的间距 */
            font-size: 17px;
        }

        .text {
            /* 文本的样式 */
            margin-right: 150px; /* 右侧的间距 */
            font-size: 17px;
            color: #fe7a16;
        }

        .last_text {
            /* 文本的样式 */
            margin-right: 150px; /* 右侧的间距 */
            font-size: 17px;
            color: #959595;
        }

        .self_button{
            display: flex;
            margin-right: 25px; /* 右侧的间距 */
            font-size: 14px;
            color: #959595;
            margin-bottom: 18px;
        }

        .icon1 {
            /* 图标样式 */
            display: inline-block;
            width: 15px; /* 设置图标的宽度 */
            height: 15px; /* 设置图标的高度 */
            vertical-align: middle; /* 垂直对齐方式设为居中 */
            background-size: cover;
            background-image: url("/static/images/l1.png");
        }

        .icon2 {
            /* 图标样式 */
            display: inline-block;
            width: 15px; /* 设置图标的宽度 */
            height: 15px; /* 设置图标的高度 */
            vertical-align: middle; /* 垂直对齐方式设为居中 */
            background-size: cover;
            background-image: url("/static/images/l2.png");
        }

        .icon3 {
            /* 图标样式 */
            display: inline-block;
            width: 15px; /* 设置图标的宽度 */
            height: 15px; /* 设置图标的高度 */
            vertical-align: middle; /* 垂直对齐方式设为居中 */
            background-size: cover;
            background-image: url("/static/images/l3.png");
        }

        .icon4 {
            /* 图标样式 */
            display: inline-block;
            width: 15px; /* 设置图标的宽度 */
            height: 15px; /* 设置图标的高度 */
            vertical-align: middle; /* 垂直对齐方式设为居中 */
            background-size: cover;
            background-image: url("/static/images/l4.png");
        }

        .icon5 {
            /* 图标样式 */
            display: inline-block;
            width: 15px; /* 设置图标的宽度 */
            height: 15px; /* 设置图标的高度 */
            vertical-align: middle; /* 垂直对齐方式设为居中 */
            background-size: cover;
            background-image: url("/static/images/l5.png");
        }

        .icon6 {
            /* 图标样式 */
            display: inline-block;
            width: 15px; /* 设置图标的宽度 */
            height: 15px; /* 设置图标的高度 */
            vertical-align: middle; /* 垂直对齐方式设为居中 */
            background-size: cover;
            background-image: url("/static/images/l6.png");
        }

</style>

<div class="first_header">{% include "kits/first_header.html" %}</div>

    {% for club in clubs %}
        <div class="block">
            <div class="first_text">
                <a href="{% url 'club:club_detail' club.id %}">
                <h4 class="list-group-item-heading">{{ club.name }}</h4></a>
            </div>
            <div class="text"><p class="list-group-item-heading">{{ club.num_of_mem }}成员</p></div>
            <div class="text">
                {% with total_fans=club.fans.count %}
                <p class="list-group-item-heading">{{ total_fans }}关注</p>
                {% endwith %}
            </div>
            <div class="last_text"><p class="list-group-item-heading">{{ club.Aboutme |slice:'70'|linebreaks }}</p></div>
        </div>

        <div class="block1">
            <div class="self_button">
                <span class="icon1"></span><a href="{% url 'club:manage_member' club.id %}"><p>成员管理</p></a>
            </div>
            <div class="self_button">
                <span class="icon2"></span><a href="{% url 'club:manage_clubInfo' club.id %}"><p>社团信息管理</p></a>
            </div>
            <div class="self_button">
                <span class="icon3"></span><a href="{% url 'club:create_activity' club.id %}"><p>为社团创建活动</p></a>
            </div>
            <div class="self_button">
                <span class="icon4"></span><a href="{% url 'club:list_activity' club.id %}"><p>管理社团活动</p></a>
            </div>
            <div class="self_button">
                <span class="icon5"></span><a href="{% url 'club:list_activity' club.id %}"><p>新增社团闲置物品</p></a>
            </div>
            <div class="self_button">
                <span class="icon6"></span><a href="{% url 'club:create_ad' club.id %}"><p>创建社团广告</p></a>
            </div>
            <div class="self_button">
                <span class="icon6"></span><a href="{% url 'club:manage_ad' club.id %}"><p>管理社团广告</p></a>
            </div>
            <div class="self_button">
                <span class="icon6"></span><a href=http://1.94.53.254:9090/student/registerClub><p>创建社团账号</p></a>
            </div>
        </div>

    {% empty %}
    <div class="first_header">{% include "kits/footer.html" %}</div>
    {% endfor %}
    <div class="block"></div>
    {% include "paginator.html" %}


{% endblock %}