manage_club/account/urls.py
from django.urls import re_path as url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path
from captcha.views import captcha_image
from django.conf.urls import include


app_name='account'

urlpatterns = [
    url(r'^login/$',views.user_login,name="user_login"),
    path(r'logout/', auth_views.LogoutView.as_view(template_name="account/logout.html"), name='logout'),
    url(r'^register/$',views.register,name="user_register"),
    path('password-change/',
         auth_views.PasswordChangeView.as_view(template_name='registration/password_change_form.html',
                                               success_url='../password-change-done/'), name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),
    url(r'^password-reset/$',auth_views.PasswordResetView.as_view(template_name="account/password_reset_form.html",
                                                          email_template_name="account/password_reset_email.html",
                                                          subject_template_name="account/password_reset_subject.txt",
                                                          success_url="../password-reset-done"),name="password_reset"),
    url(r'^password-reset-done/$',auth_views.PasswordResetDoneView.as_view(template_name="account/password_reset_done.html"),name="password_Reset_done"),
    url(r'^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        auth_views.PasswordResetConfirmView.as_view(template_name="account/password_reset_confirm.html",success_url="../../../password-reset-complete/"),
        name="password_reset_confirm"),
    url(r'^password-reset-complete/$',auth_views.PasswordResetCompleteView.as_view(template_name="account/password_reset_complete.html"),
        name="password_reset_complete"),
    url(r'^my-information/$',views.myself,name="my_information"),
    url(r'^my-information/(?P<user_id>\d+)/$',views.myself_version,name="my_information"),
    url(r'^edit-my-information/$',views.myself_edit,name="edit_my_information"),
    url(r'^my-image/$',views.my_image,name="my_image"),
    url(r'^search/$',views.search,name="search"),
    
    path('captcha/', include('captcha.urls')),

]

manage_club/club/urls.py
from django.urls import re_path as url
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.urls import path

app_name = "club"

urlpatterns = [
    url(r'^create-club/$',views.create_club,name="create_club"),
    url(r'^delete-club/$',views.delete_club,name="delete_club"),
    url(r'^list-club/$',views.list_club,name="list_club"),
    url(r'^club-detail/(?P<club_id>\d+)/$',views.list_club_detail,name="club_detail"),
    url(r'^send-message/$',views.send_message,name="send_message"),
    url(r'^my-send/$',views.my_send,name="my_send"),
    url(r'^my-send-type/(?P<type>\d+)/$', views.my_send_type, name="my_send_type"),
    url(r'^my-receive/$',views.my_recceived,name="my_receive"),
    url(r'^message-detail/(?P<message_id>\d+)/$',views.message_detail,name="message_detail"),
    url(r'^join-club/(?P<club_id>\d+)/$',views.join_club,name="join_club"),
    url(r'^exit-club/$',views.exit_club,name="exit_club"),
    url(r'^confirm-join/(?P<club_id>\d+)/$',views.confirm_join,name="confirm_join"),
    url(r'^my_club/$',views.my_club,name="my_club"),
    url(r'^manage-Myclub/$',views.manage_Myclub,name="manage_Myclub"),
    url(r'^manage-member/(?P<club_id>\d+)/$',views.manage_member,name="manage_member"),
    url(r'^delete-member/(?P<club_id>\d+)/$',views.delete_member,name="delete_member"),
    url(r'^manage-clubInfo/(?P<club_id>\d+)/$',views.manage_clubInfo,name="manage_clubInfo"),
    url(r'^club-image/(?P<club_id>\d+)/$',views.club_image,name="club_image"),
    url(r'^create-activity/(?P<club_id>\d+)/$',views.create_activity,name="create_activity"),
    url(r'^list-activity/(?P<club_id>\d+)/$',views.list_activity,name="list_activity"),
    url(r'^activity-detail/(?P<activity_id>\d+)/(?P<club_id>\d+)/$',views.activity_detail,name="activity_detail"),
    url(r'^activity-detail/(?P<activity_id>\d+)/$',views.activity_detail_version,name="activity_detail"),
    url(r'^delete-activity/$',views.delete_activity,name="delete_activity"),
    url(r'^all-activity/$',views.all_activity,name="all_activity"),
    url(r'^my-activity/$',views.my_activity,name="my_activity"),
    url(r'^fan-Club/$',views.fan_Club,name="fan_Club"),

    url(r'^create-ad/(?P<club_id>\d+)/$',views.create_ad,name="create_ad"),
    url(r'^list-ads/(?P<club_id>\d+)/$',views.list_ads,name="list_ads"),
    url(r'^manage_ad/(?P<club_id>\d+)/$',views.manage_ad,name="manage_ad"),
    url(r'^view_ad_lists/(?P<club_id>\d+)/$',views.view_ad_lists,name="view_ad_lists"),
    url(r'^ad-detail-owner/(?P<ad_id>\d+)/$',views.ad_detail_owner,name="ad_detail_owner"),
    url(r'^ad-detail-other/(?P<ad_id>\d+)/$',views.ad_detail_other,name="ad_detail_other"),
    url(r'^ad-detail-edit/(?P<ad_id>\d+)/$',views.ad_detail_edit,name="ad_detail_edit"),
    url(r'^delete_ad/$',views.delete_ad,name="delete_ad"),
]

manage_club/home/urls.py
from django.urls import re_path as url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^homepage/$',views.homepage,name="homepage"),
]

manage_club/manage_club/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import re_path as url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    url(r'^account/',include('account.urls',namespace='account')),
    url(r'^club/', include('club.urls', namespace='club')),
    url(r'^home/',include("home.urls",namespace='home')),
    url(r'^trade/',include('trade.urls',namespace='trade')),
    path('captcha/', include('captcha.urls')),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

manage_club/templates/kits/first_header.html
<!DOCTYPE html>
<html>
<head>
    <title>自定义块样式</title>
    <style>
        .first_header {
            background-color: #d8f4fc;
            color: #0e8ecf;
            padding: 10px;
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .first_header p {
            margin: 0 auto;
            font-size: 20px;
            padding-left: 5px;
        }

    </style>
</head>
<body>
    <div class="first_header" style="height: 35px;">
        <p>我管理的社团</p>
    </div>

</body>
</html>

manage_club/templates/kits/first_header1.html
<!DOCTYPE html>
<html>
<head>
    <title>自定义块样式</title>
    <style>
        .first_header {
            background-color: #d8f4fc;
            color: #0e8ecf;
            padding: 10px;
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .first_header p {
            margin: 0 auto;
            font-size: 20px;
            padding-left: 5px;
        }

    </style>
</head>
<body>
    <div class="first_header" style="height: 35px;">
        <p>我加入的社团</p>
    </div>

</body>
</html>

manage_club/templates/kits/first_header2.html
<!DOCTYPE html>
<html>
<head>
    <title>自定义块样式</title>
    <style>
        .first_header {
            background-color: #d8f4fc;
            color: #0e8ecf;
            padding: 10px;
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .first_header p {
            margin: 0 auto;
            font-size: 20px;
            padding-left: 5px;
        }

    </style>
</head>
<body>
    <div class="first_header" style="height: 35px;">
        <p>全部社团</p>
    </div>

</body>
</html>

manage_club/templates/kits/first_header3.html
<!DOCTYPE html>
<html>
<head>
    <title>自定义块样式</title>
    <style>
        .first_header {
            background-color: #d8f4fc;
            color: #0e8ecf;
            padding: 10px;
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .first_header p {
            margin: 0 auto;
            font-size: 20px;
            padding-left: 5px;
        }

    </style>
</head>
<body>
    <div class="first_header" style="height: 35px;">
        <p>最新活动</p>
    </div>

</body>
</html>

manage_club/templates/kits/footer.html
<!DOCTYPE html>
<html>
<head>
    <title>自定义块样式</title>
    <style>
        .first_header {
            background-color: #d8f4fc;
            color: #0e8ecf;
            padding: 10px;
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .first_header p {
            margin: 0 auto;
            font-size: 20px;
            padding-left: 5px;
        }

    </style>
</head>
<body>
    <div class="first_header" style="height: 35px;">
        <p>对不起，这里暂时没有您要找的内容捏</p>
    </div>

</body>
</html>

manage_club/templates/kits/header.html
<!--
 * @FileName: 
 * @Description: 
 * @Autor: Liujunjie/Aries-441
 * @StudentNumber: 521021911059
 * @Date: 2023-10-09 23:59:22
 * @E-mail: sjtu.liu.jj@gmail.com/sjtu.1518228705@sjtu.edu.cn
 * @LastEditTime: 2023-10-14 19:23:39
-->
{% load static %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="https://www.sjtu.com"><img src="{% static '/images/genshin.png' %}"
                                                                         width="100px" height="30px"></a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="tablist">
                <li><a href="{% url 'home:homepage' %}">HOME</a></li>
                <li><a href="{% url 'club:my_club' %}">我加入的社团</a></li>
                <li><a href="{% url 'club:manage_Myclub' %}">我管理的社团</a></li>
                <li><a href="{% url 'club:list_club' %}">全部社团</a></li>
                <li><a href="{% url 'club:all_activity' %}">最新活动</a></li>
                <li><a href= http://1.94.53.254:10000/>社团闲置物品交易</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="margin-right: 10px">
                {% if user.is_authenticated %}
                <li>
                    <div class="dropdown" style="margin-top: 8px">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown">
                            {{ user.username }}<span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:my_information' %}">个人信息</a></li>
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                            <li><a id="reset-password-btn">重置密码</a></li>
                            <li><a href="{% url 'club:send_message' %}">联络他人</a></li>
                            <li><a href="{% url 'club:my_receive' %}">收到的消息</a></li>
                            <li><a href="{% url 'club:my_send' %}">发出的消息</a></li>
                            <li><a href="{% url 'club:create_club' %}">创建社团</a></li>
                            <li><a href="{% url 'account:search' %}">查找用户</a></li>
                        </ul>
                     </div>
                </li>

                <li><a id="logout-btn">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:user_login' %}">LOGIN</a></li>
                <li><a href="{% url 'account:user_register' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<script>
    // 获取重置密码按钮元素
    var resetPasswordBtn = document.getElementById("reset-password-btn");
    // 添加点击事件监听器
    resetPasswordBtn.addEventListener("click", function(event) {
      event.preventDefault(); // 阻止默认的链接行为
      // 弹出确认对话框
      var confirmReset = confirm("确定要重置密码吗？这个行为会使你退出登录");
      // 如果用户点击了确认按钮，则继续执行重置密码操作
      if (confirmReset) {
        // 执行重置密码操作
        window.location.href = "{% url 'account:password_reset' %}"; 
      }
    });

    // 获取退出登录按钮元素
    var logoutBtn = document.getElementById("logout-btn");
    // 添加点击事件监听器
    logoutBtn.addEventListener("click", function(event) {
      event.preventDefault(); // 阻止默认的链接行为
      // 弹出确认对话框
      var confirmReset = confirm("确定要退出当前登录账号吗？");
      // 如果用户点击了确认按钮，则继续执行退出登录操作
      if (confirmReset) {
        // 执行退出登录操作
        window.location.href = "{% url 'account:logout' %}"; 
      }
    });
</script>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>

manage_club/templates/kits/homepage_header.html
<!DOCTYPE html>
<html>
<head>
    <title>自定义块样式</title>
    <style>
        .first_header {
            background-color: #d8f4fc;
            color: #0e8ecf;
            padding: 10px;
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .first_header p {
            margin: 0 auto;
            font-size: 20px;
            padding-left: 5px;
        }

    </style>
</head>
<body>
    <div class="first_header" style="height: 35px;">
        <p>欢迎来到社团管理主页</p>
    </div>

</body>
</html>